// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAveBBHOtZJEJxXtNkNBPKPohpkU44xuoo',
    appId: '1:1067743300847:web:4c0443be19719229a3df1a',
    messagingSenderId: '1067743300847',
    projectId: 'talkio-app-97894',
    authDomain: 'talkio-app-97894.firebaseapp.com',
    storageBucket: 'talkio-app-97894.firebasestorage.app',
    measurementId: 'G-8QGFRM028Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbHk3SW0BgVJBgRpDeDjFIqUUCwXigyA',
    appId: '1:1067743300847:android:3cf66b5444e9a12ea3df1a',
    messagingSenderId: '1067743300847',
    projectId: 'talkio-app-97894',
    storageBucket: 'talkio-app-97894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnUNrlHPcMx4Oyb47ajkIAhLcm_HRcq5k',
    appId: '1:1067743300847:ios:89cbca7a64a64132a3df1a',
    messagingSenderId: '1067743300847',
    projectId: 'talkio-app-97894',
    storageBucket: 'talkio-app-97894.firebasestorage.app',
    iosBundleId: 'com.example.talkioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnUNrlHPcMx4Oyb47ajkIAhLcm_HRcq5k',
    appId: '1:1067743300847:ios:89cbca7a64a64132a3df1a',
    messagingSenderId: '1067743300847',
    projectId: 'talkio-app-97894',
    storageBucket: 'talkio-app-97894.firebasestorage.app',
    iosBundleId: 'com.example.talkioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAveBBHOtZJEJxXtNkNBPKPohpkU44xuoo',
    appId: '1:1067743300847:web:37db9bef79e84eaaa3df1a',
    messagingSenderId: '1067743300847',
    projectId: 'talkio-app-97894',
    authDomain: 'talkio-app-97894.firebaseapp.com',
    storageBucket: 'talkio-app-97894.firebasestorage.app',
    measurementId: 'G-M5FSW93JDE',
  );

}